### ISSUE TITLE
Lux-dataframe when saved as html is not rendering properly.

### ISSUE THREAD

**Issue by GorakhNigam** [lux-org/lux#405]
I am trying to save all the charts after adding intent to dataframe using df.save_as_html(). The Html that I am getting is showing all the charts except for the current visualization chart, when opening in the chrome-browser.
![lux-issue](https://user-images.githubusercontent.com/22448472/127887097-c7d2fa5f-4671-4c19-bf67-c26653e1650e.JPG)

**Comment by dorisjlee** [comment]
Hi @GorakhNigam, Thank you for reporting this issue! You're right that the Current visualization seems a bit off when exported to HTML. I was able to reproduce this issue on my end. I'll be looking into how we can fix this. Thanks!

**Comment by dorisjlee** [comment]
Tried debugging this, chart data seems to be embedded inside export.html, but jupyter-widget/html-manager is not rendering this correctly.

**Comment by cgarciae** [comment]
I believe this was solved in lux-org/lux-widget#103.

**Comment by GorakhNigam** [comment]
Hi @cgarciae I tried after upgrading lux-widget by using the command you mentioned, but the issue persists still.

**Comment by GorakhNigam** [comment]
Hi @cgarciae, I tried after upgrading the lux-widget but it did not work for me.

**Comment by dorisjlee** [comment]
Hey @GorakhNigam, What is the issue that you are seeing? After you upgrade to the newest release of lux by running `pip install --upgrade lux-api` in your terminal and then in your Jupyter notebook, try running:
``` python
import lux
lux.debug_info()
```
This should return a message regarding any installation issues. Please send us the debug info you're seeing. Thanks!

**Comment by GorakhNigam** [comment]
Hi @dorisjlee, There is no horizontal scroll bar to scroll the graphs horizontally in the saved Html. 

I didn't find any error in the lux installation

>>> import lux
>>> lux.debug_info()
Package Versions
----------------
               Version
        python           3.7.6
           lux           0.5.1
        pandas           1.3.5
     luxwidget          0.1.11
    matplotlib           3.5.1
        altair           4.2.0
       IPython        7.32.0\r
     ipykernel         6.9.2\r
    ipywidgets         7.7.0\r
jupyter_client         7.1.2\r
  jupyter_core         4.9.2\r
jupyter_server not installed\r
    jupyterlab not installed\r
      nbclient        0.5.13\r
     nbconvert         6.4.4\r
      nbformat         5.2.0\r
      notebook        6.4.10\r
     qtconsole not installed\r
     traitlets         5.1.1\r

Widget Setup
