### ISSUE TITLE
[BUG] Unable to scroll in jupyterlab

### ISSUE THREAD

**Issue by wcbeard** [lux-org/lux#411]
**Describe the bug**

**To Reproduce**
Please describe the steps needed to reproduce the behavior. For example:
1. Open up binder [exercise link](https://mybinder.org/v2/gh/lux-org/lux-binder/master?urlpath=lab/tree/exercise) from Github page
2. Open 0-Lux-Overview.ipynb
3. Execute first 3 code cells

**Expected behavior**
Text at the bottom of the viz says 'Scroll for 12 more charts.' There is no scroll bar. When I click on the arrows, nothing happens. When I hover over the arrows, they change shades, but clicking them does nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/379413/129976123-6387dc7a-054a-4ea4-8e6a-70e2e1413131.png)

**Additional context**

**Comment by dorisjlee** [comment]
Thanks for reporting this issue @wcbeard! This was also an issue reported in the Slack community.
It seems like which the horizontal scroll still works on the trackpad, the manual scrollbar disappeared.
We should look into adding back the scrollbar to accommodate for different browsers/systems.

**Comment by dorisjlee** [comment]
Fixed [this bug in lux-widget](https://github.com/lux-org/lux-widget/commit/edb6a5ac58808990506c3abd1af8a811146e6f99)
![Screen Shot 2021-09-10 at 10 56 44 AM](https://user-images.githubusercontent.com/5554675/132897018-bf8a66fc-6e0c-466c-b68b-671d931475f6.png). This fix will be part of the upcoming release!
Thanks again for letting us know about this issue!

**Comment by zufanka** [comment]
Hello! I still have this problem in jupyter lab, see versions below:

python 7.3.0
jupyterlab                       3.2.4
lux-api                            0.4.0
lux-widget                       0.1.10

browser: Firefox 94.0
os: Fedora 33

Is there something I can do to fix it?
Thank you very much, I really like the library!

**Comment by dorisjlee** [comment]
Hi @zufanka, Thanks for letting us know! We should have fixed this in the version of Lux that you're on, so it's strange that you are running into issues. Can you try using Chrome to see if this fixes the problem? If not, please send us a screenshot of what issues you're seeing so we can help debug this!
