### ISSUE TITLE
LuxDataFrame's __setitem__ super call throws SettingWithCopyWarning

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux#93]
The parent call for `__setitem__` seems to trigger a SettingWithCopyWarning. 

```
# First cell
df = pd.read_csv("https://github.com/lux-org/lux-datasets/blob/master/data/olympic.csv?raw=True")
df["Year"] = pd.to_datetime(df["Year"],format="%Y")

from lux.vis.Vis import Vis
vis = Vis(["Weight","Height"],df)
vis

# Next cell
df = vis.data
df["xBin"] = pd.cut(df["Weight"], bins=30)
df["yBin"] = pd.cut(df["Height"], bins=30)
df
```
Warning: 
```
lux/core/frame.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(LuxDataFrame, self).__setitem__(key, value)
```
![image](https://user-images.githubusercontent.com/5554675/94154582-a0946380-feb0-11ea-80a2-355461957cd3.png)

**Comment by westernguy2** [comment]
Adding the fix to issue #79 by adding an else case for data type computation should fix the issue for `pd.cut`. However, adding this fix leads us to another error (same example as above):

![Screen Shot 2020-09-24 at 11 10 38 PM](https://user-images.githubusercontent.com/32151899/94232580-2cab8880-febb-11ea-93fa-f4e43cd22a9b.png)

The `SettingWithCopyWarning` is caused mainly by issues detailed [here](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy). 

The fix that removes the warning involves swapping out `vis.data[list(attributes)]` for `vis.data.loc[:,list(attributes)]` inside `PandasExecutor.execute`.

**Comment by dorisjlee** [comment]
Replaced indexing with `.loc`, however, this did not fix the issue. The issue stems from .agg in groupby, this warning is suppressed since behavior is expected.
